// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYSQIY1zWTVmkFErwWgO97VidCVJHuVQ',
    appId: '1:209868366155:web:3cf9e9f30c4b10a2cdc8ce',
    messagingSenderId: '209868366155',
    projectId: 'emotionicon-f4917',
    authDomain: 'emotionicon-f4917.firebaseapp.com',
    storageBucket: 'emotionicon-f4917.appspot.com',
    measurementId: 'G-M3RX1381VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr49R3A9UxBrUmhv2XVYrthvV8XmZ_5WY',
    appId: '1:209868366155:android:383399423dd32a76cdc8ce',
    messagingSenderId: '209868366155',
    projectId: 'emotionicon-f4917',
    storageBucket: 'emotionicon-f4917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzOwJsFRXVK89_HwHqZ0GHhPoazvS9uN4',
    appId: '1:209868366155:ios:2bc894f0667276d6cdc8ce',
    messagingSenderId: '209868366155',
    projectId: 'emotionicon-f4917',
    storageBucket: 'emotionicon-f4917.appspot.com',
    iosClientId: '209868366155-31rrfh4e839bu8vfhob0psovpqqvls5l.apps.googleusercontent.com',
    iosBundleId: 'com.taquangkhoi.emotionIcon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzOwJsFRXVK89_HwHqZ0GHhPoazvS9uN4',
    appId: '1:209868366155:ios:01c342e926f15956cdc8ce',
    messagingSenderId: '209868366155',
    projectId: 'emotionicon-f4917',
    storageBucket: 'emotionicon-f4917.appspot.com',
    iosClientId: '209868366155-0jj5prulc69vlvqhu49ifptfud431rr5.apps.googleusercontent.com',
    iosBundleId: 'com.taquangkhoi.emotionIcon.RunnerTests',
  );
}
